### ISSUE TITLE
About running speed

### ISSUE THREAD

**Issue by hxm1150310617** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#122]
Hi, I ran the demo.py with gpu GTX1080Ti on my own video and get only about 5Fps. I wonder if it's my problem or something else.

**Comment by Daniil-Osokin** [comment]
Hi! I believe it is due to network results post-processing. You can measure network inference, it should be fast. We provide[ C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) for the best inference time. Python demo is for quick results preview, however there is ongoing #121 PR, which will speed up Python part.

**Comment by hxm1150310617** [comment]
thank you so much for replying.

**Comment by Daniil-Osokin** [comment]
Ok, closing.
