### ISSUE TITLE
Difference in generate paf and parse keypoint with Open pose

### ISSUE THREAD

**Issue by tucachmo2202** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#174]
Hi, thanks for great job!
May I am not clear, but I find your repo using other way to generate paf with Openpose and different way to parse connections respectively?

**Comment by tucachmo2202** [comment]
Hi, thanks for replying soon.
I know that they are same format but in Openpose the author use greedy and munkres algorithm to group keypoints while your code just using greedy algorithm?

**Comment by Daniil-Osokin** [comment]
This is because the code follows [this](https://arxiv.org/pdf/1811.12004.pdf) work, which optimizes ["Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields"](https://openaccess.thecvf.com/content_cvpr_2017/papers/Cao_Realtime_Multi-Person_2D_CVPR_2017_paper.pdf). So no munkres algorithm here.

**Comment by tucachmo2202** [comment]
Oh, I understand. Great! I've read your paper and find "Author reported inference speed of 4.2 fps on 2.8GHz Quad-core CPU and 10 fps on Jetson TX2". Do you use C++ code when testing in Jetson TX2?

**Comment by Daniil-Osokin** [comment]
These results from some other paper. But it is better to use C++ code for the speed benchmarking.

**Comment by tucachmo2202** [comment]
I got it. Thank you very much!
