### ISSUE TITLE
Validation on custom dataset

### ISSUE THREAD

**Issue by renziver** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#200]
I have a custom dataset that has only 14 keypoints, however, COCO Eval expects 17 keypoints, What is the right way of modifying the `val.py` script for custom datasets w/ fewer keypoints.

Based on `val.py` data is being converted to COCO format through `convert_to_coco_format` function but it is tightly coupled or designed for COCO Person (17 keypoint) dataset.

I tried the following changes in `val.py` but i'm encountering errors.
```
# keypoints = [0] * 17* 3
# to_coco_map = [0, -1, 6, 8, 10, 5, 7, 9, 12, 14, 16, 11, 13, 15, 2, 1, 4, 3]

keypoints = [0] * 14 * 3
to_coco_map = [0,1,2,3,4,5,6,7,8,9,10,11,12,13]
```

```
stage1_heatmaps_loss: 608.5013868713379
stage2_pafs_loss:     271.34232315063474
stage2_heatmaps_loss: 289.14791915893557
Validation...
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/home/jupyter/lightweight-human-pose-estimation.pytorch/val.py", line 137, in evaluate
    coco_keypoints, scores = convert_to_coco_format(pose_entries, all_keypoints)
  File "/home/jupyter/lightweight-human-pose-estimation.pytorch/val.py", line 74, in convert_to_coco_format
    keypoints[to_coco_map[position_
```

**Comment by Daniil-Osokin** [comment]
Hi! If you want to evaluate custom keypoints with `pycocotools`:
1. Read formats of [annotation](https://cocodataset.org/#format-data) and [results](https://cocodataset.org/#format-results) as the first step.
2. Then you need to prepare your annotation according this format. For you I have prepared small example of annotation and detection for a custom dataset of "triangle" object (however it is not a good idea to detect triangle by keypoints, because all corners looks the same, but it is ok for demonstration purposes): [keypoints_sample.zip](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/files/6832327/keypoints_sample.zip).
3. After that adjust [sigmas](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L523) (number and value), which control maximum allowable shift of predicted keypoint from annotation, more about them in ["1.3. Tuning OKS"](https://cocodataset.org/#keypoints-eval).
4. When you have got the format and adjusted sigmas in `pycocotools` properly, run [`run_coco_eval`](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L17) with your annotation and some sample detections to see if it works and shows output.

After these steps you will have the feeling how to modify detected keypoints output in `val.py` for your use case.

**Comment by renziver** [comment]
Thank you @Daniil-Osokin :)
