### ISSUE TITLE
python demo

### ISSUE THREAD

**Issue by ZHAJIANGMIAN2002** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#329]
Hello, my environment is deployed on a remote server and uses vscode ssh to connect. However, there is no camera on my remote server, so an error will be reported when using `--video 0`. Now I just want to run a python demo of a video without using the camera for real-time detection. How should I set the parameters of the following code?
`python demo.py --checkpoint-path <path_to>/checkpoint_iter_370000.pth --video 0`

**Comment by Daniil-Osokin** [comment]
Hi! You can just pass video file path instead of camera id. Also you may add `cv2.imwrite("{0:05d}.jpg".format(frame_id))` instead of this [cv2.imshow](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L128) and remove `cv2.waitKey()`. To get `frame_id`, change [this line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L91) to `for frame_id, img in enumerate(image_provider):`.

**Comment by ZHAJIANGMIAN2002** [comment]
Tks,it really helps me!
