### ISSUE TITLE
about mobilenet_sgd_68.848.pth.tar

### ISSUE THREAD

**Issue by violetnotfat** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#5]
Hi!Thanks for your works.
When I train from MobileNet weights，the output is shown below
![image](https://user-images.githubusercontent.com/48441193/54171753-7fc71180-44b6-11e9-97a6-2f806678651a.png)
There seems to be no pre-trained parameters.

**Comment by Daniil-Osokin** [comment]
Hi! The output is ok. `mobilenet_sgd_68.848.pth.tar` contains just parameters for the [feature extractor](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/models/with_mobilenet.py#L92), so the rest layers (`cpm` and `stages`) are initialized by default, and output says, that there are no pre-trained parameters for them. This checkpoint is from classification [network](https://github.com/marvis/pytorch-mobilenet), I've uploaded it on GoogleDrive, since original one is in Baidu.

**Comment by violetnotfat** [comment]
Thank you！

**Comment by danielanojan** [comment]
Hi can you provide the link of gdrive of his path?

**Comment by Daniil-Osokin** [comment]
Here you are: [link](https://drive.google.com/file/d/18Ya27IAhILvBHqV_tDp0QjDFvsNNy-hv/view?usp=sharing).

**Comment by biechifanle** [comment]
May I ask where you downloaded the model, I can’t download the model after passing the link, if you know, please let me know, thank you very much

**Comment by Daniil-Osokin** [comment]
Hi! I have checked the link above, it works for me. You may try to download it here: https://github.com/wjc852456/pytorch-mobilenet-v1, if you have a Baidu account.

**Comment by wzl-GitHubs** [comment]
遥遥领先！遥遥领先！
