### ISSUE TITLE
Is it possible to make it work for hand keypoint?

### ISSUE THREAD

**Issue by LexTran** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#71]
Hi, me again, I'm really sorry I have a lot of questions
Is it possible to modify the code so it can work for hand keypoints? Do I need to train it from the beginning with hand keypoints dataset or not? Can it work by just modifing the keypoint imformation? I hope someone can help me, it would be really nice of you guys.

**Comment by Daniil-Osokin** [comment]
Hi, it is totally possible (but will require some effort). The easiest way is to have hand dataset in [COCO format](http://cocodataset.org/#format-data) and modify keypoints grouping arrays, some details are in #56 (also other issues may help). When data is ready, and code properly modified, you can start training from MobileNet weights.

**Comment by LexTran** [comment]
OK， I'll try, Thanks

**Comment by LexTran** [comment]
@Daniil-Osokin  Hi, I was trying make a custom dataset in COCO format, but I don't know how can I make a coco format keypoints dataset, is there some tools I can use for annotations?  Hope you can give me some advice, thanks.

**Comment by Daniil-Osokin** [comment]
You can try [cvat](https://github.com/opencv/cvat) or [coco-annotator](https://github.com/jsbroks/coco-annotator). I believe the easiest way is to adopt existing dataset to COCO format, check example [here](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html). However you can also adopt the code (instead of dataset) to support needed dataset.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
